import { useRef } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  Text,
  Box,
  Button,
  SlideFade,
  Image,
  useMediaQuery,
  Flex,
  Link,
  UnorderedList,
  ListItem,
} from "@chakra-ui/react";
import Particles from "../components/Shared/Particles";
import MyCarousel from "../components/Shared/CardCarousel";

// icons
import { FaLinkedinIn, FaGithub } from "react-icons/fa";

export default function Home() {
  const [isDesktop] = useMediaQuery("(min-width: 1048px)");
  const ref = useRef();
  const clickScrollTo = () => ref.current.scrollIntoView();
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* HOME - START */}
        <SlideFade in="true" delay={"2"}>
          <Flex
            position={"relative"}
            flexDirection={{ base: "column", lg: "row" }}
            minH="100vh"
            alignItems={"center"}
            justifyContent="center"
            padding="8"
          >
            <Box display={"flex"} height="100%" width={"100%"}>
              <Box height="100%" width={"100%"}>
                <Text
                  bgGradient="linear(to-r, #1c7ed6 , #22b8cf)"
                  bgClip="text"
                  fontSize={{ lg: "6xl", base: "5xl" }}
                  fontWeight="extrabold"
                >
                  Fakultas Seni Rupa dan Desain.
                </Text>
                <Text
                  bgGradient="linear(to-r, #1c7ed6 , #22b8cf)"
                  bgClip="text"
                  fontSize={{ lg: "3xl", base: "5xl" }}
                  fontWeight="bold"
                >
                  Universitas Ruangguru CAMP.
                </Text>
                <Button
                  colorScheme="linkedin"
                  variant="outline"
                  width={{ base: "70%", md: "50%", lg: "20%" }}
                  marginTop="4"
                  onClick={clickScrollTo}
                >
                  Learn More
                </Button>
              </Box>
            </Box>
            {/* {isDesktop && (
            <Box height={"100%"} bgColor="blue.200">
              test
            </Box>
          )} */}
            {/* {!isDesktop && <Particles />} */}
            <Particles />
          </Flex>
        </SlideFade>

        {/* HOME - END */}

        {/* ABOUT - START */}
        <main className={styles.main} id="visi-misi" ref={ref}>
          <SlideFade in="true">
            <Box
              display={{ lg: "flex" }}
              flexDirection={{ lg: "column" }}
              bgColor="white"
              shadow={"lg"}
              padding={{ base: 4, lg: 10 }}
              rounded={"md"}
              minH={"50vh"}
            >
              <Text
                bgGradient="linear(to-r, #1c7ed6 , #22b8cf)"
                bgClip="text"
                textAlign={{ lg: "center" }}
                fontSize={{ lg: "5xl", base: "3xl" }}
                fontWeight="extrabold"
              >
                Visi dan Misi
              </Text>
              <Box gap="4" alignItems={"center"} marginTop="6">
                <Text
                  textAlign={{ lg: "center" }}
                  fontSize={{ lg: "3xl", base: "3xl" }}
                  fontWeight="bold"
                  color="gray.500"
                  marginTop="4"
                >
                  Visi
                </Text>
                <Text
                  textAlign={{ lg: "center" }}
                  fontSize={{ lg: "xl", base: "xl" }}
                  fontWeight="bold"
                  color="gray.400"
                  marginTop="2"
                >
                  Memaksakan transformasi kesenian 4.0 yang memadukan antara
                  seni dan teknologi.
                </Text>
                <Text
                  textAlign={{ lg: "center" }}
                  fontSize={{ lg: "3xl", base: "3xl" }}
                  fontWeight="bold"
                  color="gray.500"
                  marginTop="4"
                >
                  Misi
                </Text>
                <Box
                  color="gray.400"
                  fontWeight={"bold"}
                  textAlign="center"
                  gap="2"
                >
                  <Text>Mendamaikan sengekta antara UI/UX dan Developer</Text>
                  <Text>
                    Mengedukasi masyarakat bahwa developer juga punya sisi
                    artisik
                  </Text>
                  <Text>
                    Memperluas domain developer yang tidak hanya bisa ngoding,
                    benerin printer, wifi, tetapi juga bisa desain memakai
                    software seperti photoshop, figma, dll
                  </Text>
                </Box>
                {/* <Text
                  textAlign={{ lg: "center" }}
                  fontSize={{ lg: "xl", base: "xl" }}
                  fontWeight="bold"
                  color="gray.400"
                  marginTop="2"
                >
                  Memaksakan transformasi kesenian 4.0 yang memadukan antara
                  seni dan teknologi.
                </Text> */}
              </Box>
            </Box>
          </SlideFade>
        </main>
        {/* ABOUT - END */}

        {/* PROJECTS - START */}
        <main className={styles.main}>
          <SlideFade in="true">
            <Box
              display={{ lg: "flex" }}
              flexDirection={{ lg: "column" }}
              // bgColor="white"
              // shadow={"lg"}
              padding={{ base: 4, lg: 10 }}
              // rounded={"md"}
              minH={"50vh"}
              justifyContent="center"
            >
              <Text
                bgGradient="linear(to-r, #1c7ed6 , #22b8cf)"
                bgClip="text"
                // textAlign={{ lg: "center" }}
                fontSize={{ lg: "5xl", base: "3xl" }}
                fontWeight="extrabold"
              >
                Struktur Organisasi
              </Text>
              <MyCarousel />
            </Box>
          </SlideFade>
        </main>

        {/* PROJECTS - END */}
      </div>
      {/* FOOTER - START */}
      <footer className={styles.footer}>
        <SlideFade in="true">
          <Box
            display={{ lg: "flex" }}
            flexDirection={{ lg: "column" }}
            // bgColor="white"
            // shadow={"lg"}
            padding={{ base: 4, lg: 10 }}
            // rounded={"md"}
            minH={"50vh"}
            justifyContent="center"
            textAlign={"center"}
          >
            <Text
              // bgGradient="linear(to-r, #1c7ed6 , #22b8cf)"
              // bgClip="text"
              // textAlign={{ lg: "center" }}
              color={"white"}
              fontSize={{ lg: "5xl", base: "3xl" }}
              fontWeight="extrabold"
            >
              Universitas Ruangguru CAMP
            </Text>
            <Text
              color="white"
              fontSize={{ lg: "3xl", base: "5xl" }}
              fontWeight="bold"
            >
              Fakultas Seni Rupa dan Desain (FSRD)
            </Text>
            {/* <MyCarousel /> */}
          </Box>
        </SlideFade>
      </footer>

      {/* FOOTER - END */}
    </>
  );
}
