import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  Text,
  Box,
  Button,
  SlideFade,
  Image,
  useMediaQuery,
  Flex,
  Link,
} from "@chakra-ui/react";
import Particles from "../components/Shared/Particles";
import MyCarousel from "../components/Shared/CardCarousel";

// icons
import { FaLinkedinIn, FaGithub } from "react-icons/fa";

export default function Home() {
  const [isDesktop] = useMediaQuery("(min-width: 1048px)");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* HOME - START */}
      <SlideFade in="true" delay={"2"}>
        <Flex
          position={"relative"}
          flexDirection={{ base: "column", lg: "row" }}
          minH="100vh"
          alignItems={"center"}
          justifyContent="center"
          padding="8"
        >
          <Box display={"flex"} height="100%" width={"100%"}>
            <Box height="100%" width={"100%"}>
              <Text
                bgGradient="linear(to-r, #1c7ed6 , #22b8cf)"
                bgClip="text"
                fontSize={{ lg: "6xl", base: "5xl" }}
                fontWeight="extrabold"
              >
                Fakultas Seni Rupa dan Desain.
              </Text>
              <Text
                bgGradient="linear(to-r, #1c7ed6 , #22b8cf)"
                bgClip="text"
                fontSize={{ lg: "3xl", base: "5xl" }}
                fontWeight="bold"
              >
                Universitas Ruangguru CAMP.
              </Text>
              <Button
                colorScheme="linkedin"
                variant="outline"
                width={{ base: "70%", md: "50%", lg: "20%" }}
                marginTop="4"
              >
                Learn More
              </Button>
            </Box>
          </Box>
          {/* {isDesktop && (
            <Box height={"100%"} bgColor="blue.200">
              test
            </Box>
          )} */}
          {/* {!isDesktop && <Particles />} */}
          <Particles />
        </Flex>
      </SlideFade>

      {/* HOME - END */}

      {/* ABOUT - START */}
      <main className={styles.main}>
        <SlideFade in="true">
          <Box
            display={{ lg: "flex" }}
            flexDirection={{ lg: "column" }}
            bgColor="white"
            shadow={"lg"}
            padding={{ base: 4, lg: 10 }}
            rounded={"md"}
            minH={"50vh"}
          >
            <Text
              bgGradient="linear(to-r, #1c7ed6 , #22b8cf)"
              bgClip="text"
              textAlign={{ lg: "center" }}
              fontSize={{ lg: "5xl", base: "3xl" }}
              fontWeight="extrabold"
            >
              Visi dan Misi
            </Text>
            <Box display={"flex"} gap="4" alignItems={"center"} marginTop="6">
              <div></div>
            </Box>

            <Box
              display={"flex"}
              gap="2"
              marginTop="4"
              flexDirection={{ base: "column", md: "row" }}
            >
              <Box display={"flex"} gap="2" width={"100%"}></Box>
              <Box display={"flex"} gap="2"></Box>
            </Box>
          </Box>
        </SlideFade>
      </main>
      {/* ABOUT - END */}

      {/* PROJECTS - START */}
      <main className={styles.main}>
        <SlideFade in="true">
          <Box
            display={{ lg: "flex" }}
            flexDirection={{ lg: "column" }}
            // bgColor="white"
            // shadow={"lg"}
            padding={{ base: 4, lg: 10 }}
            // rounded={"md"}
            minH={"50vh"}
            justifyContent="center"
          >
            <Text
              bgGradient="linear(to-r, #1c7ed6 , #22b8cf)"
              bgClip="text"
              // textAlign={{ lg: "center" }}
              fontSize={{ lg: "5xl", base: "3xl" }}
              fontWeight="extrabold"
            >
              Struktur Organisasi
            </Text>
            <MyCarousel />
          </Box>
        </SlideFade>
      </main>

      {/* PROJECTS - END */}
    </div>
  );
}
