import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  Text,
  Box,
  Button,
  SlideFade,
  Image,
  useMediaQuery,
  Flex,
  Link,
} from "@chakra-ui/react";
import Particles from "../components/Shared/Particles";
import MyCarousel from "../components/Shared/CardCarousel";

// icons
import { FaLinkedinIn, FaGithub } from "react-icons/fa";

export default function Home() {
  const [isDesktop] = useMediaQuery("(min-width: 1048px)");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* HOME - START */}
      <SlideFade in="true" delay={"2"}>
        <Flex
          position={"relative"}
          flexDirection={{ base: "column", lg: "row" }}
          minH="100vh"
          alignItems={"center"}
          justifyContent="center"
          padding="8"
        >
          <Box display={"flex"} height="100%" width={"100%"}>
            <Box height="100%" width={"100%"}>
              <Text
                bgGradient="linear(to-r, #1c7ed6 , #22b8cf)"
                bgClip="text"
                fontSize={{ lg: "6xl", base: "5xl" }}
                fontWeight="extrabold"
              >
                Make something cool by code.
              </Text>
              <Button
                colorScheme="linkedin"
                variant="outline"
                width={{ base: "70%", md: "50%", lg: "20%" }}
                marginTop="4"
              >
                Learn More
              </Button>
            </Box>
          </Box>
          {/* {isDesktop && (
            <Box height={"100%"} bgColor="blue.200">
              test
            </Box>
          )} */}
          {/* {!isDesktop && <Particles />} */}
          <Particles />
        </Flex>
      </SlideFade>

      {/* HOME - END */}

      {/* ABOUT - START */}
      <main className={styles.main}>
        <SlideFade in="true">
          <Box
            display={{ lg: "flex" }}
            flexDirection={{ lg: "column" }}
            bgColor="white"
            shadow={"lg"}
            padding={{ base: 4, lg: 10 }}
            rounded={"md"}
            minH={"50vh"}
          >
            <Text
              bgGradient="linear(to-r, #1c7ed6 , #22b8cf)"
              bgClip="text"
              textAlign={{ lg: "center" }}
              fontSize={{ lg: "5xl", base: "3xl" }}
              fontWeight="extrabold"
            >
              About me
            </Text>
            <Box display={"flex"} gap="4" alignItems={"center"} marginTop="6">
              <Image
                borderRadius="full"
                boxSize={{ base: "120px", lg: "150px" }}
                src={"/assets/images/indra.jpeg"}
                alt="Indra"
              />
              <div>
                <Text
                  color="gray.700"
                  // bgClip="text"
                  fontSize={{ lg: "2xl", base: "xl" }}
                  fontWeight="bold"
                >
                  Indra Ahmad Firdaus
                </Text>
                <Text
                  color="gray.500"
                  // bgClip="text"
                  fontSize={{ lg: "2xl", base: "md" }}
                  // fontWeight="bold"
                >
                  Software Engineer
                </Text>
              </div>
            </Box>
            <Text
              marginTop="4"
              color="gray.500"
              // bgClip="text"
              fontSize={{ lg: "2xl", base: "md" }}
              // fontWeight="bold"
            >
              Casual and moderate tech-savvy who able to write code and also
              loves to teach other how to do so.
            </Text>
            <Box
              display={"flex"}
              gap="2"
              marginTop="4"
              flexDirection={{ base: "column", md: "row" }}
            >
              <Box display={"flex"} gap="2" width={"100%"}>
                <Button
                  colorScheme="linkedin"
                  // variant="outline"
                  width={{ base: "70%", md: "50%", lg: "20%" }}
                  marginTop="4"
                >
                  Projects
                </Button>
                <Button
                  colorScheme="linkedin"
                  variant="ghost"
                  bg="linkedin.50"
                  width={{ base: "70%", md: "50%", lg: "20%" }}
                  marginTop="4"
                >
                  Resume
                </Button>
              </Box>
              <Box display={"flex"} gap="2">
                <Link
                  href="https://www.linkedin.com/in/indra-ahmad-firdaus/"
                  isExternal
                >
                  <Button
                    colorScheme="linkedin"
                    variant="ghost"
                    marginTop="4"
                    marginLeft={{ base: 0, md: "auto" }}
                  >
                    <FaLinkedinIn target="_blank" size={25} />
                  </Button>
                </Link>

                <Link href="https://github.com/indraahmadfirdaus/" isExternal>
                  <Button
                    colorScheme="linkedin"
                    variant="ghost"
                    marginTop="4"
                    // marginLeft={{ base: 0, md: "auto" }}
                  >
                    <FaGithub target="_blank" size={25} />
                  </Button>
                </Link>
              </Box>
            </Box>
          </Box>
        </SlideFade>
      </main>
      {/* ABOUT - END */}

      {/* PROJECTS - START */}
      <main className={styles.main}>
        <SlideFade in="true">
          <Box
            display={{ lg: "flex" }}
            flexDirection={{ lg: "column" }}
            // bgColor="white"
            // shadow={"lg"}
            padding={{ base: 4, lg: 10 }}
            // rounded={"md"}
            minH={"50vh"}
            justifyContent="center"
          >
            <Text
              bgGradient="linear(to-r, #1c7ed6 , #22b8cf)"
              bgClip="text"
              // textAlign={{ lg: "center" }}
              fontSize={{ lg: "5xl", base: "3xl" }}
              fontWeight="extrabold"
            >
              Latest Projects
            </Text>
            <MyCarousel />
          </Box>
        </SlideFade>
      </main>

      {/* PROJECTS - END */}
    </div>
  );
}
